version: 2
jobs:
  get_data:
    machine:
      image: circleci/classic:201711-01
    working_directory: /tmp/data
    steps:
      - restore_cache:
          keys:
            - data-v1-{{ .Revision }}
            - data-v1-
      - run:
          name: Get ds114_test1
          command: |
            mkdir -p /tmp/data
            if [[ ! -d /tmp/data/ds114_test1 ]]; then
              wget -c -O ~/ds114_test1.tar \
              "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e54a326c613b01d7d3ed90" && \
              tar xf ~/ds114_test1.tar -C /tmp/data && \
              rm ~/ds114_test1.tar;
            else
              echo "ds114_test1 was cached"
            fi
      - run:
          name: Get ds114_test2
          command: |
            if [[ ! -d /tmp/data/ds114_test2 ]]; then
              wget -c -O ~/ds114_test2.tar \
              "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e549f9b83f6901d457d162" && \
              tar xf ~/ds114_test2.tar -C /tmp/data && \
              rm ~/ds114_test2.tar;
            else
              echo "ds114_test2 was cached"
            fi
      - run:
          name: Create ds114_test2_1ses
          command: |
            if [[ ! -d /tmp/data/ds114_test2_1ses ]]; then
              cp -r /tmp/data/ds114_test2 /tmp/data/ds114_test2_1ses && \
              rm -r /tmp/data/ds114_test2_1ses/sub-*/ses-retest
            else
              echo "ds114_test2_1ses was cached"
            fi
      - run:
          name: Get ds114_test1_freesurfer
          command: |
            if [[ ! -d /tmp/data/ds114_test1_freesurfer ]]; then
              wget -c -O ~/ds114_test1_freesurfer.tar \
              "https://osf.io/j6zk2/?action=download&version=1" && \
              tar xf ~/ds114_test1_freesurfer.tar -C /tmp/data && \
              mv /tmp/data/ds114_test1_freesurfer_precomp_v6.0.0 /tmp/data/ds114_test1_freesurfer && \
              rm ~/ds114_test1_freesurfer.tar;
            else
              echo "ds114_test1_freesurfer was cached"
            fi
      - run:
          name: Get ds114_test2_freesurfer
          command: |
            if [[ ! -d /tmp/data/ds114_test2_freesurfer ]]; then
              wget -c -O ~/ds114_test2_freesurfer.tar \
              "https://osf.io/yhzzj/?action=download&version=1" && \
              tar xf ~/ds114_test2_freesurfer.tar -C /tmp/data && \
              mv /tmp/data/ds114_test2_freesurfer_precomp_v6.0.0 /tmp/data/ds114_test2_freesurfer && \
              rm ~/ds114_test2_freesurfer.tar;
            else
              echo "ds114_test2_freesurfer was cached"
            fi
      - run:
          name: Get ds114_test1_tracula_precomp
          command: |
            if [[ ! -d /tmp/data/ds114_test1_tracula_precomp ]]; then
              wget -c -O ~/ds114_test1_tracula_precomp.tar \
              "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/5882af28594d9001f447f03a" && \
              tar xf ~/ds114_test1_tracula_precomp.tar -C /tmp/data && \
              rm ~/ds114_test1_tracula_precomp.tar;
            else
              echo "ds114_test1_tracula_precomp was cached"
            fi
      - run:
          name: Get ds114_test2_tracula_precomp
          command: |
            if [[ ! -d /tmp/data/ds114_test2_tracula_precomp ]]; then
              wget -c -O ~/ds114_test2_tracula_precomp.tar \
              "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/5882b3c3594d9001f047f031" && \
              tar xf ~/ds114_test2_tracula_precomp.tar -C /tmp/data && \
              rm ~/ds114_test2_tracula_precomp.tar;
            else
              echo "ds114_test2_tracula_precomp was cached"
            fi
      - save_cache:
         key: data-v1-{{ .Revision }}-{{ epoch }}
         paths:
            - /tmp/data

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - get_data:
          filters:
            tags:
              only: /.*/
      # - build:
      #     filters:
      #       tags:
      #         only: /.*/
      # - test:
      #     requires:
      #       - get_data
      #       - build
      #     filters:
      #       tags:
      #         only: /.*/
      # - deploy:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: master
      #       tags:
      #         only: /.*/
